AWSTemplateFormatVersion: '2010-09-09'
Description: Disaster Response System Infrastructure

Resources:

  IncidentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Incidents
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: incidentId
          AttributeType: S
      KeySchema:
        - AttributeName: incidentId
          KeyType: HASH

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: DisasterLambdaRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDBAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:Scan
                  - dynamodb:UpdateItem
                Resource: !GetAtt IncidentsTable.Arn

              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: !Ref IncidentNotificationTopic

  CreateIncidentLambda:
      Type: AWS::Lambda::Function
      Properties:
        FunctionName: CreateIncidentFunction
        Runtime: python3.12
        Handler: create_incident.lambda_handler
        Role: !GetAtt LambdaExecutionRole.Arn
        Code:
          S3Bucket: hinesh-disaster-lambda-code-2026
          S3Key: create_incident.zip
        Timeout: 10 

  GetIncidentsLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: GetIncidentsFunction
      Runtime: python3.12
      Handler: get_incidents.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: hinesh-disaster-lambda-code-2026
        S3Key: get_incidents.zip
      Timeout: 10

  GetIncidentsIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt GetIncidentsLambda.Arn
      PayloadFormatVersion: "2.0"

  GetIncidentsRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: "GET /incidents"
      Target: !Join 
        - /
        - - integrations
          - !Ref GetIncidentsIntegration
      
  GetIncidentsPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref GetIncidentsLambda
      Principal: apigateway.amazonaws.com

  HttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: DisasterHttpApi
      ProtocolType: HTTP 

  LambdaIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt CreateIncidentLambda.Arn
      PayloadFormatVersion: "2.0"

  CreateIncidentRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: "POST /incidents"
      Target: !Join 
        - /
        - - integrations
          - !Ref LambdaIntegration

  ApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref HttpApi
      StageName: prod
      AutoDeploy: true

  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref CreateIncidentLambda
      Principal: apigateway.amazonaws.com

  UpdateIncidentLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: UpdateIncidentFunction
      Runtime: python3.12
      Handler: update_incident.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: hinesh-disaster-lambda-code-2026
        S3Key: update_incident.zip
      Timeout: 10

  UpdateIncidentIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt UpdateIncidentLambda.Arn
      PayloadFormatVersion: "2.0"

  UpdateIncidentRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: "PUT /incidents/{id}"
      Target: !Join 
        - /
        - - integrations
          - !Ref UpdateIncidentIntegration

  UpdateIncidentPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref UpdateIncidentLambda
      Principal: apigateway.amazonaws.com

  IncidentNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: IncidentNotificationTopic

Outputs:
  ApiEndpoint:
    Description: API Endpoint
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/prod"